### ISSUE TITLE
请问这个实现和论文中开源的实现有何区别？

### ISSUE THREAD

**Issue by shandianshan** [chaoql/rag-best-practices#1]
你好，感谢您的工作。请问您的实现和论文中开源的实现有何区别

**Comment by chaoql** [comment]
这个仓库是我在阅读论文后，对其中所采用的技术进行学习并练手的项目。其代码结构以面向过程的方式呈现，结构较为清晰，我认为这种方式对于初学者来说更加方便入门学习。

**Comment by chaoql** [comment]
> 你好，感谢您的工作。请问您的实现和论文中开源的实现有何区别

这个仓库是我在阅读论文后，对其中所采用的技术进行学习并练手的项目。其代码结构以面向过程的方式呈现，结构较为清晰，我认为这种方式对于初学者来说更加方便入门学习。
